dist: xenial
language: minimal

services:
  - docker

env:
  global:
    - SLUG="${TRAVIS_REPO_SLUG/docker-/}"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t ${SLUG} .
  - docker inspect --type=image ${SLUG}
  - docker run --name ${SLUG/!(\/)\/} -d -p 5050:5050 ${SLUG}
  - sleep 60 # Wait for server to finish starting up.
  - docker logs ${SLUG/!(\/)\/}
